### PR TITLE
Fix Detox build on android

### PR DESCRIPTION
**Pull request by Andarius**
Fixes detox issue when building the app on android: https://github.com/wix/Detox/issues/2712

### CODE REVIEW

**Review by edeckers — APPROVED** [review]
LGTM. Thank you!

**Comment by Andarius** [comment]
Thank you for your work!

**Comment by Andarius** [comment]
@edeckers, is it possible to release a new version? So that I add back this lib rather than a custom branch?

**Comment by edeckers** [comment]
Sure thing! If I find the time I'll do it today, but it might have to wait until Sunday.

**Pull request merged**
